package edu.nju.common;

/**
 * interest labels
 * @author cuihao
 */
public enum LabelType {
    WEB,ACTIVERECORD,APP,API,FRAMEWORK,CMS,DJANGO,
    EMACS,IRC,MAC,MANAGEMENT,LINUX,WINDOWS,INTERFACE,
    OS,SERVER,SOURCE,TEXTMATE,TOOL,WEBSITE,PULGIN,
    JSON,TEMPLATE,LIBRARY,UI,DATABASE,OTHER
}
