package edu.nju.git.type;

public enum FieldsType {
	REPOSITORY_NAMES,CONTRIBUTORS_LOGIN,COLLABORATORS_LOGIN,BRANCHES_NAMES,
	FORKS_NAMES,STARGAZERS_NAMES,SUBSCRIBERS_NAMES,
	PULLS_NUMBERS,ISSUES_NUMBERS,COMMITS_SHAS;
}
